logging:
  level:
    root: INFO
    com.thecodeslinger.externalconfig.ExternalConfigApplication: WARN

external-config:
  input:
    path: /home/bundled/thecode
  output:
    path: /home/bundled/slinger